name: Node.js CI Pipeline

on:
  push:
    branches: [ "master" ]

jobs:

test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies & Jest
        run: |
          npm install
          npm install -g jest
      - name: Run Tests
        run: jest

  deploy:
    needs: test
    runs-on: ubuntu-latest
    environment: production  # Ini yang menghubungkan ke aturan 'approval'
    steps:
      - name: Deploy ke Vercel
        # GitHub akan berhenti di sini sampai kamu klik 'Approve' di dashboard
        run: echo "Menunggu persetujuan manual untuk deploy..."
