name: Node.js CI Pipeline

on:
  push:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Run Tests
        # Perubahan ada di sini: Panggil lewat 'node' langsung
        run: node node_modules/jest/bin/jest.js
deploy:
    needs: test
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - name: Deploy ke Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.Deployment }}
        run: |
          npm install --global vercel
          # Menghubungkan otomatis & deploy
          vercel --prod --yes

          