name: Node.js CI Pipeline

on:
  push:
    branches: [ "master", "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Ambil kode dari repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    # JURUS TERAKHIR: Install Jest secara global di runner GitHub
    - name: Install Jest Global
      run: npm install -g jest

    - name: Jalankan Automated Test
      # Sekarang kita panggil jest langsung karena sudah terinstall global
      run: jest